### ISSUE TITLE
access violation when shuting down MFPlayerX sample

### ISSUE THREAD

**Issue by adaloveless** [FactoryXCode/MfPack#8]
First of all... THANKS FOR MAKING THIS!  I had to write some old MFC code to work with MediaFoundation a while ago... I am happy to see this library available for a less-cumbersome language.

Attached is screenshot of AV with call stack...  i got this error when shutting down after playing a video then stopping the video before shutting down the app.

![image](https://user-images.githubusercontent.com/40921793/99722634-88872d80-2a76-11eb-8e54-fc3f35d7ac47.png)

**Comment by FactoryXCode** [comment]
Hi, I assume this is fixed?

**Comment by adaloveless** [comment]
Issue still exists with latest code. Happens regardless of play-state, stopped, paused, playing.  Doesn't seem to be file specific, however, the file in question was a 1080p mp4 file. Compiled with Delphi 10.4.

**Comment by FactoryXCode** [comment]
Hi,
As I mentioned, the API is deprecated. When things needs to be simple, use the IMFMediaEngine (MfMediaEnginePlayer sample).
There are 2 samples using this interface.
The 3 player samples based on sessions should be used from windows 8.1 and above. 
So, when your target is Win 7 until 8.1, the simple player will do fine, from win 10: Don't use it.

Greetings, Tony.
